<a href="https://colab.research.google.com/github/B104020057/PIS2022/blob/main/EX03_02_%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E6%A6%82%E6%B3%81%E2%85%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd

data = {
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'Age': [25, 30, 35, 40, 22, 29, 38, 27, 33, 31],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'Salary': [50000, 60000, 75000, 80000, 45000, 62000, 72000, 58000, 69000, 71000],
    'Department': ['IT', 'HR', 'Finance', 'Marketing', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Finance']
}

df = pd.DataFrame(data)
df

    ID     Name  Age          City  Salary Department
0  101    Alice   25      New York   50000         IT
1  102      Bob   30   Los Angeles   60000         HR
2  103  Charlie   35       Chicago   75000    Finance
3  104    David   40       Houston   80000  Marketing
4  105      Eve   22       Phoenix   45000         IT
5  106    Frank   29  Philadelphia   62000         HR
6  107    Grace   38   San Antonio   72000    Finance
7  108    Helen   27     San Diego   58000  Marketing
8  109      Ivy   33        Dallas   69000         IT
9  110     Jack   31      San Jose   71000    Finance

In [46]:
#將薪水高於第3四分位數的人員標示為高薪
hs = df['Salary'].quantile(0.75)
hs
#np.float64(71750.0)
df['HighSalary'] = df['Salary'].apply(lambda x: 'Yes' if x > hs else 'No')
df

    ID     Name  Age          City  Salary Department HighSalary
0  101    Alice   25      New York   50000         IT         No
1  102      Bob   30   Los Angeles   60000         HR         No
2  103  Charlie   35       Chicago   75000    Finance        Yes
3  104    David   40       Houston   80000  Marketing        Yes
4  105      Eve   22       Phoenix   45000         IT         No
5  106    Frank   29  Philadelphia   62000         HR         No
6  107    Grace   38   San Antonio   72000    Finance        Yes
7  108    Helen   27     San Diego   58000  Marketing         No
8  109      Ivy   33        Dallas   69000         IT         No
9  110     Jack   31      San Jose   71000    Finance         No

In [47]:
#刪除高薪欄位
df.drop(columns=['HighSalary'])
df

    ID     Name  Age          City  Salary Department HighSalary
0  101    Alice   25      New York   50000         IT         No
1  102      Bob   30   Los Angeles   60000         HR         No
2  103  Charlie   35       Chicago   75000    Finance        Yes
3  104    David   40       Houston   80000  Marketing        Yes
4  105      Eve   22       Phoenix   45000         IT         No
5  106    Frank   29  Philadelphia   62000         HR         No
6  107    Grace   38   San Antonio   72000    Finance        Yes
7  108    Helen   27     San Diego   58000  Marketing         No
8  109      Ivy   33        Dallas   69000         IT         No
9  110     Jack   31      San Jose   71000    Finance         No

In [48]:
#使用 pd.concat() 新增資料（資料集）
new_data = [
    {'ID': 111, 'Name': 'Kevin', 'Age': 28, 'City': 'Austin', 'Salary': None, 'Department': 'IT'},
    {'ID': 112, 'Name': 'Lily', 'Age': 26, 'City': 'Seattle', 'Salary': 55000, 'Department': 'Marketing'},
    {'ID': 112, 'Name': 'Lily', 'Age': 26, 'City': 'Seattle', 'Salary': 55000, 'Department': 'Marketing'}
]

new_df = pd.DataFrame(new_data)
new_df

    ID   Name  Age     City   Salary Department
0  111  Kevin   28   Austin      NaN         IT
1  112   Lily   26  Seattle  55000.0  Marketing
2  112   Lily   26  Seattle  55000.0  Marketing

In [49]:
#合并
df = pd.concat([df, new_df], ignore_index=True)
df

     ID     Name  Age          City   Salary Department HighSalary
0   101    Alice   25      New York  50000.0         IT         No
1   102      Bob   30   Los Angeles  60000.0         HR         No
2   103  Charlie   35       Chicago  75000.0    Finance        Yes
3   104    David   40       Houston  80000.0  Marketing        Yes
4   105      Eve   22       Phoenix  45000.0         IT         No
5   106    Frank   29  Philadelphia  62000.0         HR         No
6   107    Grace   38   San Antonio  72000.0    Finance        Yes
7   108    Helen   27     San Diego  58000.0  Marketing         No
8   109      Ivy   33        Dallas  69000.0         IT         No
9   110     Jack   31      San Jose  71000.0    Finance         No
10  111    Kevin   28        Austin      NaN         IT        NaN
11  112     Lily   26       Seattle  55000.0  Marketing        NaN
12  112     Lily   26       Seattle  55000.0  Marketing        NaN

In [50]:
#找出空值的資料列，並填充空值（薪水依該部門平均值）
df.isnull().sum()

ID            0
Name          0
Age           0
City          0
Salary        1
Department    0
HighSalary    3
dtype: int64

In [51]:
#填充空值（薪水依該部門平均值）
avg_dp = df.groupby('Department')['Salary'].mean()
avg_dp

Department
Finance      72666.666667
HR           61000.000000
IT           54666.666667
Marketing    62000.000000
Name: Salary, dtype: float64

In [52]:
for i in range(len(df)):
    if pd.isnull(df.loc[i, 'Salary']):
        df.loc[i, 'Salary'] = avg_dp[df.loc[i, 'Department']]
df

     ID     Name  Age          City        Salary Department HighSalary
0   101    Alice   25      New York  50000.000000         IT         No
1   102      Bob   30   Los Angeles  60000.000000         HR         No
2   103  Charlie   35       Chicago  75000.000000    Finance        Yes
3   104    David   40       Houston  80000.000000  Marketing        Yes
4   105      Eve   22       Phoenix  45000.000000         IT         No
5   106    Frank   29  Philadelphia  62000.000000         HR         No
6   107    Grace   38   San Antonio  72000.000000    Finance        Yes
7   108    Helen   27     San Diego  58000.000000  Marketing         No
8   109      Ivy   33        Dallas  69000.000000         IT         No
9   110     Jack   31      San Jose  71000.000000    Finance         No
10  111    Kevin   28        Austin  54666.666667         IT        NaN
11  112     Lily   26       Seattle  55000.000000  Marketing        NaN
12  112     Lily   26       Seattle  55000.000000  Marketing        NaN

In [53]:
#刪除重複資料
df.drop_duplicates(inplace=True) #如果沒有用inplace的話，就要宣告覆蓋 -> df=df.drop_duplicates()
df

     ID     Name  Age          City        Salary Department HighSalary
0   101    Alice   25      New York  50000.000000         IT         No
1   102      Bob   30   Los Angeles  60000.000000         HR         No
2   103  Charlie   35       Chicago  75000.000000    Finance        Yes
3   104    David   40       Houston  80000.000000  Marketing        Yes
4   105      Eve   22       Phoenix  45000.000000         IT         No
5   106    Frank   29  Philadelphia  62000.000000         HR         No
6   107    Grace   38   San Antonio  72000.000000    Finance        Yes
7   108    Helen   27     San Diego  58000.000000  Marketing         No
8   109      Ivy   33        Dallas  69000.000000         IT         No
9   110     Jack   31      San Jose  71000.000000    Finance         No
10  111    Kevin   28        Austin  54666.666667         IT        NaN
11  112     Lily   26       Seattle  55000.000000  Marketing        NaN

In [54]:
#新增欄位 'NewSalary'，如果薪水小於平均值則薪水加 500，否則維持原薪水。
avg_salary = df['Salary'].mean()
avg_salary
#np.float64(62638.88888888888)

df['NewSalary'] = df['Salary'].apply(lambda x: x + 500 if x < avg_salary else x)
df

,ID,Name,Age,City,Salary,Department,HighSalary,NewSalary
0,101,Alice,25,New York,50000.000000,IT,No,50500.000000
1,102,Bob,30,Los Angeles,60000.000000,HR,No,60500.000000
2,103,Charlie,35,Chicago,75000.000000,Finance,Yes,75000.000000
3,104,David,40,Houston,80000.000000,Marketing,Yes,80000.000000
4,105,Eve,22,Phoenix,45000.000000,IT,No,45500.000000
5,106,Frank,29,Philadelphia,62000.000000,HR,No,62500.000000
6,107,Grace,38,San Antonio,72000.000000,Finance,Yes,72000.000000
7,108,Helen,27,San Diego,58000.000000,Marketing,No,58500.000000
8,109,Ivy,33,Dallas,69000.000000,IT,No,69000.000000
9,110,Jack,31,San Jose,71000.000000,Finance,No,71000.000000
10,111,Kevin,28,Austin,54666.666667,IT,NaN,55166.666667
11,112,Lily,26,Seattle,55000.000000,Marketing,NaN,55500.000000

In [55]:
#新增欄位 'RankSalary' 填入薪水排名。
df['RankSalary'] = df['Salary'].rank(ascending=False)
df

,ID,Name,Age,City,Salary,Department,HighSalary,NewSalary,RankSalary
0,101,Alice,25,New York,50000.000000,IT,No,50500.000000,11.0
1,102,Bob,30,Los Angeles,60000.000000,HR,No,60500.000000,7.0
2,103,Charlie,35,Chicago,75000.000000,Finance,Yes,75000.000000,2.0
3,104,David,40,Houston,80000.000000,Marketing,Yes,80000.000000,1.0
4,105,Eve,22,Phoenix,45000.000000,IT,No,45500.000000,12.0
5,106,Frank,29,Philadelphia,62000.000000,HR,No,62500.000000,6.0
6,107,Grace,38,San Antonio,72000.000000,Finance,Yes,72000.000000,3.0
7,108,Helen,27,San Diego,58000.000000,Marketing,No,58500.000000,8.0
8,109,Ivy,33,Dallas,69000.000000,IT,No,69000.000000,5.0
9,110,Jack,31,San Jose,71000.000000,Finance,No,71000.000000,4.0
10,111,Kevin,28,Austin,54666.666667,IT,NaN,55166.666667,10.0
11,112,Lily,26,Seattle,55000.000000,Marketing,NaN,55500.000000,9.0

In [56]:
#轉成整數
df[['Salary','NewSalary','RankSalary']] = df[['Salary','NewSalary','RankSalary']].astype(int)
df

,ID,Name,Age,City,Salary,Department,HighSalary,NewSalary,RankSalary
0,101,Alice,25,New York,50000,IT,No,50500,11
1,102,Bob,30,Los Angeles,60000,HR,No,60500,7
2,103,Charlie,35,Chicago,75000,Finance,Yes,75000,2
3,104,David,40,Houston,80000,Marketing,Yes,80000,1
4,105,Eve,22,Phoenix,45000,IT,No,45500,12
5,106,Frank,29,Philadelphia,62000,HR,No,62500,6
6,107,Grace,38,San Antonio,72000,Finance,Yes,72000,3
7,108,Helen,27,San Diego,58000,Marketing,No,58500,8
8,109,Ivy,33,Dallas,69000,IT,No,69000,5
9,110,Jack,31,San Jose,71000,Finance,No,71000,4
10,111,Kevin,28,Austin,54666,IT,NaN,55166,10
11,112,Lily,26,Seattle,55000,Marketing,NaN,55500,9